### Clients
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "Rita Ribeiro",
  "email": "r@r.com"
}

### Accounts

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "69231ece-6ff6-4fda-8152-7365cd39be33"
}

### Transactions

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "2f418fd4-e1f0-4257-ade2-21b04526dec8",
  "account_id_to": "a415a295-70ea-4858-ade7-e1ac73af85f2",
  "amount": 50
}